"""
File System Watcher - Monitors the Inbox folder for new files.

This is the simplest watcher implementation, perfect for the Bronze tier.
When files are dropped into the Inbox folder, this watcher creates
corresponding action files in the Needs_Action folder for Claude to process.
"""

import logging
import shutil
from pathlib import Path
from datetime import datetime

from base_watcher import BaseWatcher


class FilesystemWatcher(BaseWatcher):
    """
    Watches the Inbox folder for new files and creates action files.
    
    Usage:
        watcher = FilesystemWatcher('/path/to/vault')
        watcher.run()  # Runs indefinitely
    """
    
    def __init__(self, vault_path: str, check_interval: int = 5):
        """
        Initialize the filesystem watcher.
        
        Args:
            vault_path: Path to the Obsidian vault root
            check_interval: Seconds between checks (default: 5 for responsive file drops)
        """
        super().__init__(vault_path, check_interval)
        self.logger = logging.getLogger(self.__class__.__name__)
    
    def check_for_updates(self) -> list:
        """
        Check the Inbox folder for new files.
        
        Returns:
            List of file paths that need processing
        """
        new_files = []
        
        if not self.inbox.exists():
            return new_files
        
        # Get all files in inbox (not directories, not .md files, not .gitkeep)
        for file_path in self.inbox.iterdir():
            if file_path.is_file() and not file_path.suffix == '.md' and file_path.name != '.gitkeep':
                if str(file_path) not in self.processed_ids:
                    new_files.append(file_path)
                    self.processed_ids.add(str(file_path))
        
        return new_files
    
    def create_action_file(self, file_path: Path) -> Path:
        """
        Create an action file for the dropped file.
        
        Args:
            file_path: Path to the dropped file
            
        Returns:
            Path to the created action file
        """
        # Copy the file to Needs_Action
        dest = self.needs_action / f'FILE_{file_path.name}'
        shutil.copy2(file_path, dest)
        
        # Create metadata file
        meta_path = self.needs_action / f'FILE_{file_path.name}.meta.md'
        
        frontmatter = self.create_frontmatter(
            item_type='file_drop',
            original_name=file_path.name,
            size=file_path.stat().st_size,
            source=str(file_path)
        )
        
        content = f'''{frontmatter}

# File Drop for Processing

## File Information
- **Original Name**: {file_path.name}
- **Size**: {self._format_size(file_path.stat().st_size)}
- **Dropped At**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Instructions
A new file has been dropped into the Inbox folder for processing.
Please analyze the file content and take appropriate action based on
the Company Handbook rules.

## Suggested Actions
- [ ] Review file content
- [ ] Determine required action
- [ ] Execute action or create approval request
- [ ] Move file to appropriate location
- [ ] Update Dashboard.md

---
*Generated by FilesystemWatcher*
'''
        
        meta_path.write_text(content)
        self.logger.info(f'Copied file to: {dest}')
        
        return meta_path
    
    def _format_size(self, size_bytes: int) -> str:
        """Format file size in human-readable format."""
        for unit in ['B', 'KB', 'MB', 'GB']:
            if size_bytes < 1024:
                return f'{size_bytes:.1f} {unit}'
            size_bytes /= 1024
        return f'{size_bytes:.1f} TB'


def main():
    """Run the filesystem watcher."""
    import sys
    
    if len(sys.argv) < 2:
        print('Usage: python filesystem_watcher.py <vault_path>')
        print('Example: python filesystem_watcher.py ./AI_Employee_Vault')
        sys.exit(1)
    
    vault_path = sys.argv[1]
    
    # Setup logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    watcher = FilesystemWatcher(vault_path)
    watcher.run()


if __name__ == '__main__':
    main()
